using LadiesDressStore.Web.Models;using LadiesDressStore.Web.Services;using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
namespace LadiesDressStore.Web.Controllers;
public class AdminController(AdminApiService api):Controller{
 bool LoggedIn=>!string.IsNullOrWhiteSpace(Request.Cookies["admin_token"]);
 bool IsOwner=>string.Equals(User.FindFirstValue(ClaimTypes.Email),"admin@ubhaya.com",StringComparison.OrdinalIgnoreCase);
 public IActionResult Index()=>RedirectToAction(nameof(Login));
 public IActionResult Login(){if(LoggedIn)return RedirectToAction(nameof(Dashboard));return View();}
 [HttpGet] public IActionResult ForgotPassword()=>View(new AdminForgotPasswordViewModel());
 [HttpPost][ValidateAntiForgeryToken] public async Task<IActionResult> ForgotPassword(AdminForgotPasswordViewModel model){if(!ModelState.IsValid)return View(model);var result=await api.ForgotPassword(model.Email);if(!result.ok){ViewBag.Error=result.message.Trim('"');return View(model);}ViewBag.Success="If an active admin account matches that email, a reset link has been sent.";return View(model);}
 [HttpGet] public IActionResult ResetPassword(string? email,string? token)=>View(new AdminResetPasswordViewModel{Email=email??"",Token=token??""});
 [HttpPost][ValidateAntiForgeryToken] public async Task<IActionResult> ResetPassword(AdminResetPasswordViewModel model){if(!ModelState.IsValid)return View(model);var result=await api.ResetPassword(model.Email,model.Token,model.NewPassword);if(!result.ok){ModelState.AddModelError("",result.message.Trim('"'));return View(model);}TempData["AdminPasswordSuccess"]="Admin password reset successfully. Sign in with your new password.";return RedirectToAction(nameof(Login));}
 [HttpGet] public IActionResult ChangePassword(){if(!LoggedIn)return RedirectToAction(nameof(Login));return View(new AdminChangePasswordViewModel());}
 [HttpPost][ValidateAntiForgeryToken] public async Task<IActionResult> ChangePassword(AdminChangePasswordViewModel model){if(!LoggedIn)return RedirectToAction(nameof(Login));if(!ModelState.IsValid)return View(model);var result=await api.ChangePassword(model.CurrentPassword,model.NewPassword);if(!result.ok){ModelState.AddModelError("",result.message.Trim('"'));return View(model);}TempData["AdminPasswordSuccess"]="Your admin password has been updated.";return RedirectToAction(nameof(ChangePassword));}
 [HttpPost][ValidateAntiForgeryToken] public async Task<IActionResult> Login(string email,string password){var r=await api.Login(email,password);if(!r.ok){ViewBag.Error=r.message;return View();}var secureCookie=Request.IsHttps;Response.Cookies.Append("admin_token",r.data!.Token,new CookieOptions{HttpOnly=true,Secure=secureCookie,SameSite=SameSiteMode.Lax,MaxAge=TimeSpan.FromHours(2)});Response.Cookies.Append("admin_name",r.data.Name,new CookieOptions{HttpOnly=false,Secure=secureCookie,SameSite=SameSiteMode.Lax,MaxAge=TimeSpan.FromHours(2)});var identity=new ClaimsIdentity(new[]{new Claim(ClaimTypes.Name,r.data.Name),new Claim(ClaimTypes.Email,r.data.Email),new Claim("AdminSession","true")},CookieAuthenticationDefaults.AuthenticationScheme);await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,new ClaimsPrincipal(identity),new AuthenticationProperties{IsPersistent=true,ExpiresUtc=DateTimeOffset.UtcNow.AddHours(2)});return RedirectToAction(nameof(Dashboard));}
 public async Task<IActionResult> Logout(){Response.Cookies.Delete("admin_token");Response.Cookies.Delete("admin_name");await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);return RedirectToAction(nameof(Login));}
 public async Task<IActionResult> Dashboard(){if(!LoggedIn)return RedirectToAction(nameof(Login));return View(await api.Dashboard()??new());}
 public async Task<IActionResult> Customers(string? search=null){if(!LoggedIn)return RedirectToAction(nameof(Login));var orders=await api.Orders();var customers=orders.Where(o=>o.Customer is not null).GroupBy(o=>o.CustomerId).Select(g=>{var c=g.First().Customer!;return new AdminCustomerSummary{Id=c.Id,Name=c.Name,Email=c.Email,Mobile=c.Mobile,DateOfBirth=c.DateOfBirth,OrderCount=g.Count(),LastOrderDate=g.Max(o=>(DateTime?)o.CreatedDate)};}).OrderBy(c=>c.Name).ToList();if(!string.IsNullOrWhiteSpace(search)){var term=search.Trim();customers=customers.Where(c=>c.Name.Contains(term,StringComparison.OrdinalIgnoreCase)||(c.Email?.Contains(term,StringComparison.OrdinalIgnoreCase)??false)||(c.Mobile?.Contains(term,StringComparison.OrdinalIgnoreCase)??false)).ToList();}ViewBag.Search=search;return View(customers);}
 public async Task<IActionResult> AdminAccounts(){if(!LoggedIn)return RedirectToAction(nameof(Login));if(!IsOwner)return Forbid();try{return View(await api.AdminAccounts());}catch(Exception ex){ViewBag.Error=ex.Message;return View(new List<AdminAccountViewModel>());}}
 [HttpPost][ValidateAntiForgeryToken] public async Task<IActionResult> SaveAdminAccount(AdminAccountInput model){if(!LoggedIn)return RedirectToAction(nameof(Login));if(!IsOwner)return Forbid();try{await api.SaveAdminAccount(model);TempData["AccountMessage"]="Admin account saved.";}catch(Exception ex){TempData["AccountError"]=ex.Message;}return RedirectToAction(nameof(AdminAccounts));}
 [HttpPost][ValidateAntiForgeryToken] public async Task<IActionResult> DeleteAdminAccount(int id){if(!LoggedIn)return RedirectToAction(nameof(Login));if(!IsOwner)return Forbid();try{await api.DeleteAdminAccount(id);TempData["AccountMessage"]="Admin account deleted.";}catch(Exception ex){TempData["AccountError"]=ex.Message;}return RedirectToAction(nameof(AdminAccounts));}
 public async Task<IActionResult> Products(int page=1,int pageSize=10,int categoryId=0,string? size=null,decimal? discount=null){
  if(!LoggedIn)return RedirectToAction(nameof(Login));
  var products=await api.Products();
  var categories=await LoadCategories();
  var sizes=products.SelectMany(product=>product.Variants).Select(variant=>variant.Size).Where(value=>!string.IsNullOrWhiteSpace(value)).Distinct(StringComparer.OrdinalIgnoreCase).OrderBy(value=>value).ToList();
  var discounts=products.SelectMany(product=>product.Variants).Select(variant=>variant.Discount).Distinct().OrderBy(value=>value).ToList();
  if(categoryId>0)products=products.Where(product=>product.CategoryId==categoryId).ToList();
  if(!string.IsNullOrWhiteSpace(size)||discount.HasValue)products=products.Where(product=>product.Variants.Any(variant=>(string.IsNullOrWhiteSpace(size)||string.Equals(variant.Size,size,StringComparison.OrdinalIgnoreCase))&&(!discount.HasValue||variant.Discount==discount.Value))).ToList();
  if(pageSize!=0&&pageSize is not (5 or 10 or 15 or 50 or 100))pageSize=10;
  var productCount=products.Count;var effectivePageSize=Math.Max(1,pageSize==0?productCount:pageSize);var pageCount=Math.Max(1,(int)Math.Ceiling(productCount/(double)effectivePageSize));page=Math.Clamp(page,1,pageCount);
  ViewBag.ProductCount=productCount;ViewBag.CurrentPage=page;ViewBag.PageCount=pageCount;ViewBag.PageSize=pageSize;ViewBag.Categories=categories;ViewBag.Sizes=sizes;ViewBag.Discounts=discounts;ViewBag.SelectedCategoryId=categoryId;ViewBag.SelectedSize=size;ViewBag.SelectedDiscount=discount;
  return View(products.Skip((page-1)*effectivePageSize).Take(effectivePageSize).ToList());
 }
 public async Task<IActionResult> CreateProduct(){if(!LoggedIn)return RedirectToAction(nameof(Login));ViewBag.Categories=await LoadCategories();return View("ProductForm",new AdminProductInput { Variants = [new AdminProductVariantInput()] });}
 public async Task<IActionResult> EditProduct(int id){if(!LoggedIn)return RedirectToAction(nameof(Login));var p=await api.Product(id);if(p is null)return NotFound();var categories=await LoadCategories();if(categories.Count==0&&!string.IsNullOrWhiteSpace(p.Category))categories.Add(new CategoryViewModel{Id=p.CategoryId,Name=p.Category});ViewBag.Categories=categories;return View("ProductForm",p);}
 [HttpPost][ValidateAntiForgeryToken][RequestSizeLimit(510_000_000)][RequestFormLimits(MultipartBodyLengthLimit=510_000_000)] public async Task<IActionResult> SaveProduct(AdminProductInput model,IFormFile? image,List<IFormFile>? subImages,List<IFormFile>? productVideos,bool removeImage){if(!LoggedIn)return RedirectToAction(nameof(Login));try{if(model.CategoryId<=0){ModelState.AddModelError(nameof(model.CategoryId),"Choose a category before saving.");ViewBag.Categories=await LoadCategories();return View("ProductForm",model);}if(image is null||image.Length==0){if(removeImage)model.ImageUrl=string.Empty;}var saved=await api.SaveProduct(model);if(saved is null){ModelState.AddModelError("","Unable to save product.");ViewBag.Categories=await LoadCategories();return View("ProductForm",model);}if(saved.CategoryId!=model.CategoryId)throw new InvalidOperationException($"The backend returned CategoryId {saved.CategoryId} after saving CategoryId {model.CategoryId}. Restart the API backend and retry.");if(image is not null&&image.Length>0){var url=await api.UploadImage(saved.Id,image);saved.ImageUrl=url??saved.ImageUrl;}if(subImages is { Count: > 0 })await api.UploadImages(saved.Id,subImages);if(productVideos is { Count: > 0 })await api.UploadVideos(saved.Id,productVideos);return RedirectToAction(nameof(Products));}catch(Exception ex){ModelState.AddModelError("",ex.Message);var categories=await LoadCategories();if(categories.Count==0&&!string.IsNullOrWhiteSpace(model.Category))categories.Add(new CategoryViewModel{Id=model.CategoryId,Name=model.Category});ViewBag.Categories=categories;return View("ProductForm",model);}}
 public async Task<IActionResult> Categories(int page=1,int pageSize=10){if(!LoggedIn)return RedirectToAction(nameof(Login));var categories=await LoadCategories();if(pageSize!=0&&pageSize is not (5 or 10 or 15 or 50 or 100))pageSize=10;var count=categories.Count;ViewBag.HomePageCategoryCount=categories.Count(category=>category.ShowOnHomePage);var effectivePageSize=Math.Max(1,pageSize==0?count:pageSize);var pageCount=Math.Max(1,(int)Math.Ceiling(count/(double)effectivePageSize));page=Math.Clamp(page,1,pageCount);ViewBag.ItemCount=count;ViewBag.CurrentPage=page;ViewBag.PageCount=pageCount;ViewBag.PageSize=pageSize;return View(categories.Skip((page-1)*effectivePageSize).Take(effectivePageSize).ToList());}
 [HttpPost][ValidateAntiForgeryToken][RequestSizeLimit(12000000)][RequestFormLimits(MultipartBodyLengthLimit=12000000)] public async Task<IActionResult> SaveCategory(int id,string name,bool showOnHomePage,IFormFile? image,int page=1,int pageSize=10){if(!LoggedIn)return RedirectToAction(nameof(Login));try{var category=await api.SaveCategory(new CategoryViewModel{Id=id,Name=name,ShowOnHomePage=showOnHomePage});if(image is { Length: > 0 })await api.UploadCategoryImage(category.Id,image);TempData["CategoryMessage"]="Category saved.";}catch(Exception ex){TempData["CategoryError"]=ex.Message;}return RedirectToAction(nameof(Categories),new{page,pageSize});}
 [HttpPost][ValidateAntiForgeryToken] public async Task<IActionResult> DeleteCategory(int id,int page=1,int pageSize=10){if(!LoggedIn)return RedirectToAction(nameof(Login));try{await api.DeleteCategory(id);TempData["CategoryMessage"]="Category deleted.";}catch(Exception ex){TempData["CategoryError"]=ex.Message;}return RedirectToAction(nameof(Categories),new{page,pageSize});}
 [HttpPost][ValidateAntiForgeryToken] public async Task<IActionResult> DeleteProduct(int id,int page=1,int pageSize=10,int categoryId=0,string? size=null,decimal? discount=null){if(LoggedIn)await api.DeleteProduct(id);return RedirectToAction(nameof(Products),new{page,pageSize,categoryId,size,discount});}
 [HttpPost][ValidateAntiForgeryToken] public async Task<IActionResult> DeleteProductImage(int id,int imageId){if(!LoggedIn)return Unauthorized(new{error="Admin session expired. Sign in again."});try{await api.DeleteProductImage(id,imageId);return Ok(new{success=true});}catch(Exception ex){return StatusCode(StatusCodes.Status502BadGateway,new{error=ex.Message});}}
 public async Task<IActionResult> Inventory(int page=1,int pageSize=10,string? search=null,string? category=null,string? size=null,string? stockStatus=null){
  if(!LoggedIn)return RedirectToAction(nameof(Login));
  var items=await api.Inventory();
  var categories=items.Select(item=>item.Category).Where(value=>!string.IsNullOrWhiteSpace(value)).Distinct(StringComparer.OrdinalIgnoreCase).OrderBy(value=>value).ToList();
  var sizes=items.Select(item=>item.Size).Where(value=>!string.IsNullOrWhiteSpace(value)).Distinct(StringComparer.OrdinalIgnoreCase).OrderBy(value=>value).ToList();
  if(!string.IsNullOrWhiteSpace(search))items=items.Where(item=>item.Name.Contains(search.Trim(),StringComparison.OrdinalIgnoreCase)).ToList();
  if(!string.IsNullOrWhiteSpace(category))items=items.Where(item=>string.Equals(item.Category,category,StringComparison.OrdinalIgnoreCase)).ToList();
  if(!string.IsNullOrWhiteSpace(size))items=items.Where(item=>string.Equals(item.Size,size,StringComparison.OrdinalIgnoreCase)).ToList();
  items=stockStatus?.ToLowerInvariant() switch { "out"=>items.Where(item=>item.Stock==0).ToList(), "low"=>items.Where(item=>item.Stock is >0 and <=5).ToList(), "in"=>items.Where(item=>item.Stock>5).ToList(), _=>items };
  if(pageSize!=0&&pageSize is not (5 or 10 or 15 or 50 or 100))pageSize=10;
  var itemCount=items.Count;var effectivePageSize=Math.Max(1,pageSize==0?itemCount:pageSize);var pageCount=Math.Max(1,(int)Math.Ceiling(itemCount/(double)effectivePageSize));page=Math.Clamp(page,1,pageCount);
  ViewBag.ItemCount=itemCount;ViewBag.CurrentPage=page;ViewBag.PageCount=pageCount;ViewBag.PageSize=pageSize;ViewBag.Categories=categories;ViewBag.Sizes=sizes;ViewBag.Search=search;ViewBag.SelectedCategory=category;ViewBag.SelectedSize=size;ViewBag.StockStatus=stockStatus;
  return View(items.Skip((page-1)*effectivePageSize).Take(effectivePageSize).ToList());
 }
 [HttpPost][ValidateAntiForgeryToken] public async Task<IActionResult> AdjustStock(int id,string size,int quantity,string type,string? note,int page=1,int pageSize=10,string? search=null,string? category=null,string? sizeFilter=null,string? stockStatus=null){if(LoggedIn)await api.AdjustStock(id,size,quantity,type,note);return RedirectToAction(nameof(Inventory),new{page,pageSize,search,category,size=sizeFilter,stockStatus});}
 public async Task<IActionResult> Orders(int page=1,int pageSize=10,string? search=null,string? status=null,string? paymentStatus=null){if(!LoggedIn)return RedirectToAction(nameof(Login));var orders=await api.Orders();if(!string.IsNullOrWhiteSpace(search)){var term=search.Trim();orders=orders.Where(order=>order.Id.ToString().Contains(term,StringComparison.OrdinalIgnoreCase)||(!string.IsNullOrWhiteSpace(order.Customer?.Name)&&order.Customer.Name.Contains(term,StringComparison.OrdinalIgnoreCase))||(!string.IsNullOrWhiteSpace(order.Customer?.Email)&&order.Customer.Email.Contains(term,StringComparison.OrdinalIgnoreCase))).ToList();}if(!string.IsNullOrWhiteSpace(status))orders=orders.Where(order=>string.Equals(order.Status,status,StringComparison.OrdinalIgnoreCase)).ToList();if(!string.IsNullOrWhiteSpace(paymentStatus))orders=orders.Where(order=>string.Equals(order.PaymentStatus,paymentStatus,StringComparison.OrdinalIgnoreCase)).ToList();if(pageSize!=0&&pageSize is not (5 or 10 or 15 or 50 or 100))pageSize=10;var count=orders.Count;var effectivePageSize=Math.Max(1,pageSize==0?count:pageSize);var pageCount=Math.Max(1,(int)Math.Ceiling(count/(double)effectivePageSize));page=Math.Clamp(page,1,pageCount);ViewBag.ItemCount=count;ViewBag.CurrentPage=page;ViewBag.PageCount=pageCount;ViewBag.PageSize=pageSize;ViewBag.Search=search;ViewBag.SelectedStatus=status;ViewBag.SelectedPaymentStatus=paymentStatus;return View(orders.Skip((page-1)*effectivePageSize).Take(effectivePageSize).ToList());}
 [HttpPost][ValidateAntiForgeryToken] public async Task<IActionResult> UpdateOrder(int id,string status,string paymentStatus,int page=1,int pageSize=10,string? search=null,string? filterStatus=null,string? filterPaymentStatus=null){if(LoggedIn)await api.UpdateOrder(id,status,paymentStatus);return RedirectToAction(nameof(Orders),new{page,pageSize,search,status=filterStatus,paymentStatus=filterPaymentStatus});}
 public async Task<IActionResult> Payments(int page=1,int pageSize=10,string? search=null,string? status=null,string? paymentStatus=null){if(!LoggedIn)return RedirectToAction(nameof(Login));var orders=await api.Orders();if(!string.IsNullOrWhiteSpace(search)){var term=search.Trim();orders=orders.Where(order=>order.Id.ToString().Contains(term,StringComparison.OrdinalIgnoreCase)||(!string.IsNullOrWhiteSpace(order.Customer?.Name)&&order.Customer.Name.Contains(term,StringComparison.OrdinalIgnoreCase))||(!string.IsNullOrWhiteSpace(order.Customer?.Email)&&order.Customer.Email.Contains(term,StringComparison.OrdinalIgnoreCase))).ToList();}if(!string.IsNullOrWhiteSpace(status))orders=orders.Where(order=>string.Equals(order.Status,status,StringComparison.OrdinalIgnoreCase)).ToList();if(!string.IsNullOrWhiteSpace(paymentStatus))orders=orders.Where(order=>string.Equals(order.PaymentStatus,paymentStatus,StringComparison.OrdinalIgnoreCase)).ToList();if(pageSize!=0&&pageSize is not (5 or 10 or 15 or 50 or 100))pageSize=10;var count=orders.Count;var effectivePageSize=Math.Max(1,pageSize==0?count:pageSize);var pageCount=Math.Max(1,(int)Math.Ceiling(count/(double)effectivePageSize));page=Math.Clamp(page,1,pageCount);ViewBag.ItemCount=count;ViewBag.CurrentPage=page;ViewBag.PageCount=pageCount;ViewBag.PageSize=pageSize;ViewBag.Search=search;ViewBag.SelectedStatus=status;ViewBag.SelectedPaymentStatus=paymentStatus;return View(orders.Skip((page-1)*effectivePageSize).Take(effectivePageSize).ToList());}
 private async Task<List<CategoryViewModel>> LoadCategories(){try{return await api.Categories();}catch(Exception ex){ViewBag.CategoryLoadError=$"Could not load categories from the backend. Restart the backend with the latest code. Details: {ex.Message}";return [];}}
}
