using System.Net.Http.Headers;using System.Net.Http.Json;using LadiesDressStore.Web.Models;
namespace LadiesDressStore.Web.Services;
public class AdminApiService(IHttpClientFactory factory,IHttpContextAccessor accessor){
 HttpClient Client=>factory.CreateClient("Api");
 HttpRequestMessage Request(HttpMethod method,string url){var r=new HttpRequestMessage(method,url);var t=accessor.HttpContext?.Request.Cookies["admin_token"];if(!string.IsNullOrWhiteSpace(t))r.Headers.Authorization=new AuthenticationHeaderValue("Bearer",t);return r;}
 async Task<T?> Send<T>(HttpRequestMessage r){var x=await Client.SendAsync(r);if(x.StatusCode==System.Net.HttpStatusCode.Unauthorized)return default;if(!x.IsSuccessStatusCode)throw new InvalidOperationException($"Backend API request {r.Method} {r.RequestUri} returned {(int)x.StatusCode} ({x.StatusCode}): {await ReadError(x.Content)}");return await x.Content.ReadFromJsonAsync<T>();}
 static async Task<string> ReadError(HttpContent content){var body=await content.ReadAsStringAsync();try{using var json=System.Text.Json.JsonDocument.Parse(body);var root=json.RootElement;if(root.TryGetProperty("error",out var error))return error.GetString()??body;if(root.TryGetProperty("errors",out var errors)&&errors.ValueKind==System.Text.Json.JsonValueKind.Object){var messages=errors.EnumerateObject().SelectMany(item=>item.Value.ValueKind==System.Text.Json.JsonValueKind.Array?item.Value.EnumerateArray().Select(message=>message.GetString()):[]).Where(message=>!string.IsNullOrWhiteSpace(message));return string.Join(" ",messages);}if(root.TryGetProperty("title",out var title))return title.GetString()??body;}catch(System.Text.Json.JsonException){}return body;}
 public async Task<(bool ok,string message,AdminLoginResponse? data)> Login(string email,string password){var x=await Client.PostAsJsonAsync("api/admin/auth/login",new{email,password});if(!x.IsSuccessStatusCode)return(false,await x.Content.ReadAsStringAsync(),null);return(true,"",await x.Content.ReadFromJsonAsync<AdminLoginResponse>());}
 public async Task<(bool ok,string message)> ChangePassword(string currentPassword,string newPassword){var r=Request(HttpMethod.Post,"api/admin/auth/change-password");r.Content=JsonContent.Create(new{currentPassword,newPassword});var x=await Client.SendAsync(r);return(x.IsSuccessStatusCode,await x.Content.ReadAsStringAsync());}
 public async Task<(bool ok,string message)> ForgotPassword(string email){var x=await Client.PostAsJsonAsync("api/admin/auth/forgot-password",new{email});return(x.IsSuccessStatusCode,await x.Content.ReadAsStringAsync());}
 public async Task<(bool ok,string message)> ResetPassword(string email,string token,string newPassword){var x=await Client.PostAsJsonAsync("api/admin/auth/reset-password",new{email,token,newPassword});return(x.IsSuccessStatusCode,await x.Content.ReadAsStringAsync());}
 public async Task<AdminDashboardViewModel?> Dashboard()=>await Send<AdminDashboardViewModel>(Request(HttpMethod.Get,"api/admin/dashboard"));
 public async Task<List<AdminProductInput>> Products()=>await Send<List<AdminProductInput>>(Request(HttpMethod.Get,"api/admin/products"))??[];
 public async Task<List<CategoryViewModel>> Categories()=>await Send<List<CategoryViewModel>>(Request(HttpMethod.Get,"api/admin/categories"))??[];
 public async Task<CategoryViewModel> SaveCategory(CategoryViewModel category){var r=Request(category.Id==0?HttpMethod.Post:HttpMethod.Put,category.Id==0?"api/admin/categories":$"api/admin/categories/{category.Id}");r.Content=JsonContent.Create(category);var x=await Client.SendAsync(r);if(!x.IsSuccessStatusCode)throw new InvalidOperationException(await ReadError(x.Content));return await x.Content.ReadFromJsonAsync<CategoryViewModel>()??throw new InvalidOperationException("The backend did not return the saved category.");}
 public async Task<string?> UploadCategoryImage(int id,IFormFile file){using var form=new MultipartFormDataContent();await using var stream=file.OpenReadStream();var content=new StreamContent(stream);content.Headers.ContentType=new MediaTypeHeaderValue(file.ContentType??"application/octet-stream");form.Add(content,"file",file.FileName);var r=Request(HttpMethod.Post,$"api/admin/categories/{id}/image");r.Content=form;var x=await Client.SendAsync(r);if(!x.IsSuccessStatusCode)throw new InvalidOperationException(await ReadError(x.Content));var data=await x.Content.ReadFromJsonAsync<Dictionary<string,string>>();return data?["imageUrl"];}
 public async Task DeleteCategory(int id){var x=await Client.SendAsync(Request(HttpMethod.Delete,$"api/admin/categories/{id}"));if(!x.IsSuccessStatusCode)throw new InvalidOperationException(await ReadError(x.Content));}
 public async Task<AdminProductInput?> Product(int id)=>await Send<AdminProductInput>(Request(HttpMethod.Get,$"api/admin/products/{id}"));
 public async Task<AdminProductInput?> SaveProduct(AdminProductInput p){var r=Request(p.Id==0?HttpMethod.Post:HttpMethod.Put,p.Id==0?"api/admin/products":$"api/admin/products/{p.Id}");r.Content=JsonContent.Create(new{p.Name,p.Description,p.CategoryId,p.Colors,p.ImageUrl,Variants=p.Variants.Select(v=>new{v.Size,v.Price,v.Discount,v.Stock}).ToList()});return await Send<AdminProductInput>(r);}
 public async Task<bool> DeleteProduct(int id){var x=await Client.SendAsync(Request(HttpMethod.Delete,$"api/admin/products/{id}"));return x.IsSuccessStatusCode;}
 public async Task DeleteProductImage(int productId,int imageId){var x=await Client.SendAsync(Request(HttpMethod.Delete,$"api/admin/products/{productId}/images/{imageId}"));if(!x.IsSuccessStatusCode)throw new InvalidOperationException($"Image deletion failed ({(int)x.StatusCode}): {await ReadError(x.Content)}");}
 public async Task<string?> UploadImage(int id,IFormFile file){using var form=new MultipartFormDataContent();await using var stream=file.OpenReadStream();var content=new StreamContent(stream);content.Headers.ContentType=new MediaTypeHeaderValue(file.ContentType??"application/octet-stream");form.Add(content,"file",file.FileName);var r=Request(HttpMethod.Post,$"api/admin/products/{id}/image");r.Content=form;var x=await Client.SendAsync(r);if(!x.IsSuccessStatusCode)throw new InvalidOperationException(await x.Content.ReadAsStringAsync());var data=await x.Content.ReadFromJsonAsync<Dictionary<string,string>>();return data?["imageUrl"];}
 public async Task<List<string>> UploadImages(int id,IReadOnlyList<IFormFile> files){using var form=new MultipartFormDataContent();foreach(var file in files){var content=new StreamContent(file.OpenReadStream());content.Headers.ContentType=new MediaTypeHeaderValue(file.ContentType??"application/octet-stream");form.Add(content,"files",file.FileName);}var r=Request(HttpMethod.Post,$"api/admin/products/{id}/images");r.Content=form;var x=await Client.SendAsync(r);if(!x.IsSuccessStatusCode)throw new InvalidOperationException(await x.Content.ReadAsStringAsync());return await x.Content.ReadFromJsonAsync<List<string>>()??[];}
 public async Task<List<string>> UploadVideos(int id,IReadOnlyList<IFormFile> files){using var form=new MultipartFormDataContent();foreach(var file in files){var content=new StreamContent(file.OpenReadStream());content.Headers.ContentType=new MediaTypeHeaderValue(file.ContentType??"application/octet-stream");form.Add(content,"files",file.FileName);}var r=Request(HttpMethod.Post,$"api/admin/products/{id}/videos");r.Content=form;var x=await Client.SendAsync(r);if(!x.IsSuccessStatusCode)throw new InvalidOperationException(await x.Content.ReadAsStringAsync());return await x.Content.ReadFromJsonAsync<List<string>>()??[];}
 public async Task<List<AdminInventoryItem>> Inventory()=>await Send<List<AdminInventoryItem>>(Request(HttpMethod.Get,"api/admin/inventory"))??[];
 public async Task<bool> AdjustStock(int id,string size,int quantity,string type,string? note){var r=Request(HttpMethod.Post,$"api/admin/inventory/{id}/adjust");r.Content=JsonContent.Create(new{size,quantity,type,note});var x=await Client.SendAsync(r);return x.IsSuccessStatusCode;}
 public async Task<List<AdminOrderViewModel>> Orders()=>await Send<List<AdminOrderViewModel>>(Request(HttpMethod.Get,"api/admin/orders"))??[];
 public async Task<List<AdminAccountViewModel>> AdminAccounts()=>await Send<List<AdminAccountViewModel>>(Request(HttpMethod.Get,"api/admin/accounts"))??[];
 public async Task SaveAdminAccount(AdminAccountInput account){var r=Request(account.Id==0?HttpMethod.Post:HttpMethod.Put,account.Id==0?"api/admin/accounts":$"api/admin/accounts/{account.Id}");r.Content=JsonContent.Create(account);var x=await Client.SendAsync(r);if(!x.IsSuccessStatusCode)throw new InvalidOperationException(await ReadError(x.Content));}
 public async Task DeleteAdminAccount(int id){var x=await Client.SendAsync(Request(HttpMethod.Delete,$"api/admin/accounts/{id}"));if(!x.IsSuccessStatusCode)throw new InvalidOperationException(await ReadError(x.Content));}
 public async Task<bool> UpdateOrder(int id,string status,string paymentStatus){var r=Request(HttpMethod.Put,$"api/admin/orders/{id}/status");r.Content=JsonContent.Create(new{status,paymentStatus});var x=await Client.SendAsync(r);return x.IsSuccessStatusCode;}
}
