namespace LadiesDressStore.Web.Models;
public record AdminLoginResponse(string Token,int Id,string Name,string Email);
public class CategoryViewModel { public int Id {get;set;} public string Name {get;set;}=""; public string ImageUrl {get;set;}=""; public bool ShowOnHomePage {get;set;} }
public class AdminProductInput { public int Id {get;set;} public string Name {get;set;}=""; public string Description {get;set;}=""; public int CategoryId {get;set;} public string Category {get;set;}=""; public string Colors {get;set;}=""; public string? ImageUrl {get;set;} public string? NewImageUrl {get;set;} public List<AdminProductVariantInput> Variants {get;set;}=[]; public List<ProductImageViewModel> Images {get;set;}=[]; public List<ProductVideoViewModel> Videos {get;set;}=[]; }
public class AdminProductVariantInput { public string Size {get;set;}=""; public decimal Price {get;set;} public decimal Discount {get;set;} public int Stock {get;set;} }
public class AdminDashboardViewModel { public int TotalProducts{get;set;} public int TotalOrders{get;set;} public int PendingOrders{get;set;} public int LowStock{get;set;} public int Customers{get;set;} public decimal Revenue{get;set;} }
public class AdminInventoryItem { public int Id{get;set;} public string Name{get;set;}=""; public string Category{get;set;}=""; public string Size{get;set;}=""; public int Stock{get;set;} public decimal Price{get;set;} public string ImageUrl{get;set;}=""; }
public class AdminOrderViewModel { public int Id{get;set;} public int CustomerId{get;set;} public AdminCustomer? Customer{get;set;} public decimal TotalAmount{get;set;} public string Status{get;set;}=""; public string PaymentStatus{get;set;}=""; public string ShippingAddress{get;set;}=""; public DateTime CreatedDate{get;set;} public List<AdminOrderItem> Items{get;set;}=[]; }
public class AdminCustomer { public int Id{get;set;} public string Name{get;set;}=""; public string? Email{get;set;} public string? Mobile{get;set;} }
public class AdminOrderItem { public int ProductId{get;set;} public string ProductName{get;set;}=""; public decimal Price{get;set;} public int Quantity{get;set;} public string? Size{get;set;} public string? Color{get;set;} }
